export default {
    kind: "Listing",
    data: {
        after: "t3_17pf6lr",
        dist: 26,
        modhash: "pwhpj7iows78421aa64889e08df661185692ff5ee7f56f786e",
        geo_filter: null,
        children: [
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "Scotland",
                    selftext:
                        "Welcome to the weekly what's on and tourist advice thread!\n\n\\* Do you know of any local events taking place this week that other redditors might be interested in? \n\n\\* Are you planning a trip to Scotland and need some advice on what to see or where to go? \n\nThis is the thread for you - post away! \n\nThese threads are refreshed weekly on Mondays. To see earlier threads and soak in the sage advice of yesteryear, [Click here](https://www.reddit.com/r/Scotland/search?q=What%27s+on+and+tourist+advice+thread\u0026restrict_sr=on\u0026sort=new\u0026t=all).",
                    author_fullname: "t2_6l4z3",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "What's on and tourist advice thread - week beginning November 06, 2023",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/Scotland",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    thumbnail_height: null,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17opmrs",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.75,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 4,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: null,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 4,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: true,
                    thumbnail: "self",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: true,
                    mod_note: null,
                    created: 1699228873.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "self.Scotland",
                    allow_live_comments: false,
                    selftext_html:
                        '\u003C!-- SC_OFF --\u003E\u003Cdiv class="md"\u003E\u003Cp\u003EWelcome to the weekly what\u0026#39;s on and tourist advice thread!\u003C/p\u003E\n\n\u003Cp\u003E* Do you know of any local events taking place this week that other redditors might be interested in? \u003C/p\u003E\n\n\u003Cp\u003E* Are you planning a trip to Scotland and need some advice on what to see or where to go? \u003C/p\u003E\n\n\u003Cp\u003EThis is the thread for you - post away! \u003C/p\u003E\n\n\u003Cp\u003EThese threads are refreshed weekly on Mondays. To see earlier threads and soak in the sage advice of yesteryear, \u003Ca href="https://www.reddit.com/r/Scotland/search?q=What%27s+on+and+tourist+advice+thread\u0026amp;restrict_sr=on\u0026amp;sort=new\u0026amp;t=all"\u003EClick here\u003C/a\u003E.\u003C/p\u003E\n\u003C/div\u003E\u003C!-- SC_ON --\u003E',
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qkli",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "17opmrs",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "AutoModerator",
                    discussion_type: null,
                    num_comments: 10,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/Scotland/comments/17opmrs/whats_on_and_tourist_advice_thread_week_beginning/",
                    parent_whitelist_status: "all_ads",
                    stickied: true,
                    url: "https://www.reddit.com/r/Scotland/comments/17opmrs/whats_on_and_tourist_advice_thread_week_beginning/",
                    subreddit_subscribers: 401501,
                    created_utc: 1699228873.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            }
        ],
        before: null,
    },
};
