export default {
    kind: "Listing",
    data: {
        after: "t3_17r8z90",
        dist: 5,
        modhash: "xhehv0y5gqe906096e764c873458778dd2f379ee4b1647f356",
        geo_filter: null,
        children: [
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "Scotland",
                    selftext:
                        "My mum has reuthutoid arthritis had a fall this morning nearly 4 hours late still no sign of ambulance they called around 5 am \n\nThey said not to let her eat or drink but her pain meds will stop working soon then what do I do?",
                    author_fullname: "t2_312dmucg",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Been waiting nearly 4 hours for ambulance in central Edinburgh",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/Scotland",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    thumbnail_height: null,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17r7kxa",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.92,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 124,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: null,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 124,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: true,
                    thumbnail: "self",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: true,
                    mod_note: null,
                    created: 1699514436.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "self.Scotland",
                    allow_live_comments: false,
                    selftext_html:
                        '\u003C!-- SC_OFF --\u003E\u003Cdiv class="md"\u003E\u003Cp\u003EMy mum has reuthutoid arthritis had a fall this morning nearly 4 hours late still no sign of ambulance they called around 5 am \u003C/p\u003E\n\n\u003Cp\u003EThey said not to let her eat or drink but her pain meds will stop working soon then what do I do?\u003C/p\u003E\n\u003C/div\u003E\u003C!-- SC_ON --\u003E',
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qkli",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "17r7kxa",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "ninjascotsman",
                    discussion_type: null,
                    num_comments: 114,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/Scotland/comments/17r7kxa/been_waiting_nearly_4_hours_for_ambulance_in/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.reddit.com/r/Scotland/comments/17r7kxa/been_waiting_nearly_4_hours_for_ambulance_in/",
                    subreddit_subscribers: 402785,
                    created_utc: 1699514436.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "ProgrammerHumor",
                    selftext: "",
                    author_fullname: "t2_ni8n4lby",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "areTheyStupid",
                    link_flair_richtext: [{ e: "text", t: "Meme" }],
                    subreddit_name_prefixed: "r/ProgrammerHumor",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: "meme",
                    downs: 0,
                    thumbnail_height: 74,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17r2bqx",
                    quarantine: false,
                    link_flair_text_color: "light",
                    upvote_ratio: 0.89,
                    author_flair_background_color: null,
                    ups: 3375,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: 140,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: true,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: "Meme",
                    can_mod_post: false,
                    score: 3375,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "https://b.thumbs.redditmedia.com/SKW_-7zGPuV0GHW_uSB4o3T24dyUurL33qs2HJJC75U.jpg",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    post_hint: "image",
                    content_categories: null,
                    is_self: false,
                    subreddit_type: "public",
                    created: 1699495710.0,
                    link_flair_type: "richtext",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "i.redd.it",
                    allow_live_comments: false,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest: "https://i.redd.it/tfhnfioad8zb1.jpg",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    preview: {
                        images: [
                            {
                                source: {
                                    url: "https://preview.redd.it/tfhnfioad8zb1.jpg?auto=webp\u0026s=24301dcc9139aefa9786fbb3b4216f0fb7cefef8",
                                    width: 1600,
                                    height: 856,
                                },
                                resolutions: [
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=108\u0026crop=smart\u0026auto=webp\u0026s=a6834ead1693783411e0856b7c2aa8e61b4ecb11",
                                        width: 108,
                                        height: 57,
                                    },
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=216\u0026crop=smart\u0026auto=webp\u0026s=f815983e5b62545db475c4224b9bdede18cda7a8",
                                        width: 216,
                                        height: 115,
                                    },
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=320\u0026crop=smart\u0026auto=webp\u0026s=3c0708f7ff0dc9eb30b9c8e9ee246cbe408d9148",
                                        width: 320,
                                        height: 171,
                                    },
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=640\u0026crop=smart\u0026auto=webp\u0026s=3d37d2dbecc2e7e60acbd364477a8caa47f22f8e",
                                        width: 640,
                                        height: 342,
                                    },
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=960\u0026crop=smart\u0026auto=webp\u0026s=fd23d13b22c6c68e146d9171bb40c1b1c49a9c44",
                                        width: 960,
                                        height: 513,
                                    },
                                    {
                                        url: "https://preview.redd.it/tfhnfioad8zb1.jpg?width=1080\u0026crop=smart\u0026auto=webp\u0026s=5eea4a41918eda406cd87243b558b21d2feae525",
                                        width: 1080,
                                        height: 577,
                                    },
                                ],
                                variants: {},
                                id: "ivYLPTvdZxHyeFodFQ-DX9CXZs2joOJksQxuRNo7yt4",
                            },
                        ],
                        enabled: true,
                    },
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    link_flair_template_id: "fe277d42-440f-11e8-8ec3-0eac434afc94",
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    mod_note: null,
                    distinguished: null,
                    subreddit_id: "t5_2tex6",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    num_reports: null,
                    removal_reason: null,
                    link_flair_background_color: "#373c3f",
                    id: "17r2bqx",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "TaloSi_MCX-E",
                    discussion_type: null,
                    num_comments: 435,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/ProgrammerHumor/comments/17r2bqx/aretheystupid/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://i.redd.it/tfhnfioad8zb1.jpg",
                    subreddit_subscribers: 3228828,
                    created_utc: 1699495710.0,
                    num_crossposts: 1,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "programmingmemes",
                    selftext: "",
                    author_fullname: "t2_1k000uza",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "rip",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/programmingmemes",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    thumbnail_height: 140,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17r4kpg",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.84,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 17,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: 140,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: true,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 17,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "https://a.thumbs.redditmedia.com/_GJ-acePqgsKiQ2WS-A7Y0tArieKalqk1vA0jUyyhu8.jpg",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    post_hint: "image",
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1699502613.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "i.redd.it",
                    allow_live_comments: false,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest: "https://i.redd.it/vvlile8tx8zb1.png",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    preview: {
                        images: [
                            {
                                source: {
                                    url: "https://preview.redd.it/vvlile8tx8zb1.png?auto=webp\u0026s=5bc5738d9a1b683d45e8d7ca94f359f81726b301",
                                    width: 650,
                                    height: 712,
                                },
                                resolutions: [
                                    {
                                        url: "https://preview.redd.it/vvlile8tx8zb1.png?width=108\u0026crop=smart\u0026auto=webp\u0026s=7ffc1e88626cb511ec0f31a928a9754fb355ce7d",
                                        width: 108,
                                        height: 118,
                                    },
                                    {
                                        url: "https://preview.redd.it/vvlile8tx8zb1.png?width=216\u0026crop=smart\u0026auto=webp\u0026s=84606ac2e6c6ea0146372daf29ff499ca512bc50",
                                        width: 216,
                                        height: 236,
                                    },
                                    {
                                        url: "https://preview.redd.it/vvlile8tx8zb1.png?width=320\u0026crop=smart\u0026auto=webp\u0026s=0f392dc8fcc3fe4d6c6d3c54887da40616ea9ef1",
                                        width: 320,
                                        height: 350,
                                    },
                                    {
                                        url: "https://preview.redd.it/vvlile8tx8zb1.png?width=640\u0026crop=smart\u0026auto=webp\u0026s=9b07b1fd92143a09f6cc1d8286a5ce4ad39a2d30",
                                        width: 640,
                                        height: 701,
                                    },
                                ],
                                variants: {},
                                id: "T1OBDO9AX8jEZqbbrPt0NLzIUKKMqL559C32tazJTf8",
                            },
                        ],
                        enabled: true,
                    },
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2tj0l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "17r4kpg",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "giffyfruit",
                    discussion_type: null,
                    num_comments: 1,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/programmingmemes/comments/17r4kpg/rip/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://i.redd.it/vvlile8tx8zb1.png",
                    subreddit_subscribers: 18875,
                    created_utc: 1699502613.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "Scotland",
                    selftext: "",
                    author_fullname: "t2_in7eo",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Brexit has weakened UK trade opportunities, Bank of England governor Andrew Bailey warns",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/Scotland",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: "pc",
                    downs: 0,
                    thumbnail_height: 93,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17r9sgl",
                    quarantine: false,
                    link_flair_text_color: null,
                    upvote_ratio: 0.88,
                    author_flair_background_color: "",
                    subreddit_type: "public",
                    ups: 57,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: 140,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: "Political",
                    can_mod_post: false,
                    score: 57,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "https://b.thumbs.redditmedia.com/LIRvhj_L4nY-2uaQppD6-ndmBM9XLziy0Eg4lRqQc4o.jpg",
                    edited: false,
                    author_flair_css_class: "",
                    author_flair_richtext: [],
                    gildings: {},
                    post_hint: "link",
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1699524534.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "independent.co.uk",
                    allow_live_comments: false,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://www.independent.co.uk/news/uk/politics/brexit-bank-of-england-criticism-andrew-bailey-b2443668.html",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    preview: {
                        images: [
                            {
                                source: {
                                    url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?auto=webp\u0026s=9899324e4da856565702dfd053cdf9e84b2e3445",
                                    width: 1200,
                                    height: 800,
                                },
                                resolutions: [
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=108\u0026crop=smart\u0026auto=webp\u0026s=370b523b2325cfd18598d3c61623cd68d1e2c74c",
                                        width: 108,
                                        height: 72,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=216\u0026crop=smart\u0026auto=webp\u0026s=388094f842f17d3ed4fbd3d70d8f878504a12ae9",
                                        width: 216,
                                        height: 144,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=320\u0026crop=smart\u0026auto=webp\u0026s=45325b39bad979e6b9aa9a8ebd99617dfa85b5bb",
                                        width: 320,
                                        height: 213,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=640\u0026crop=smart\u0026auto=webp\u0026s=c76684fabc02411dd577d1a21fa7625bcc1a0264",
                                        width: 640,
                                        height: 426,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=960\u0026crop=smart\u0026auto=webp\u0026s=4108d3238e7cdfaed5e29ebab0f42a63a928eebb",
                                        width: 960,
                                        height: 640,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/RD1byfrr86vjcgBILYRoRwylnv3Bu6k7Xo4zITeuC5k.jpg?width=1080\u0026crop=smart\u0026auto=webp\u0026s=e94a96dce3b8341a3fa2545ba0ebe74fc4d92dc0",
                                        width: 1080,
                                        height: 720,
                                    },
                                ],
                                variants: {},
                                id: "kxd5optjm7Flq6QTbw4CS3FKOTwbJ-9i6b5QQvXKCgA",
                            },
                        ],
                        enabled: false,
                    },
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: "",
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qkli",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: null,
                    id: "17r9sgl",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "Eggiebumfluff",
                    discussion_type: null,
                    num_comments: 18,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: "",
                    permalink: "/r/Scotland/comments/17r9sgl/brexit_has_weakened_uk_trade_opportunities_bank/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.independent.co.uk/news/uk/politics/brexit-bank-of-england-criticism-andrew-bailey-b2443668.html",
                    subreddit_subscribers: 402785,
                    created_utc: 1699524534.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "programming",
                    selftext: "",
                    author_fullname: "t2_gcwz3",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "EU to force browsers to trust government certificate authorities even if they don't meet security standards",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/programming",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    thumbnail_height: 70,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_17rbt0v",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.95,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 178,
                    total_awards_received: 0,
                    media_embed: {},
                    thumbnail_width: 140,
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 178,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "default",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    post_hint: "link",
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1699532760.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "eff.org",
                    allow_live_comments: false,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://www.eff.org/deeplinks/2023/11/article-45-will-roll-back-web-security-12-years",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: true,
                    pinned: false,
                    over_18: false,
                    preview: {
                        images: [
                            {
                                source: {
                                    url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?auto=webp\u0026s=6fa6f526a49e4add412e16a9e5f907370cf2f7fd",
                                    width: 1200,
                                    height: 600,
                                },
                                resolutions: [
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=108\u0026crop=smart\u0026auto=webp\u0026s=1cee4bc76182974ec6403cc447d889b572a71b59",
                                        width: 108,
                                        height: 54,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=216\u0026crop=smart\u0026auto=webp\u0026s=3a725ccedf0c8f745f535a1179f1abff649e3c52",
                                        width: 216,
                                        height: 108,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=320\u0026crop=smart\u0026auto=webp\u0026s=91451e40451d504ccacb45890e76f377f2cc7418",
                                        width: 320,
                                        height: 160,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=640\u0026crop=smart\u0026auto=webp\u0026s=312af75713f319c4a4779edb586df700a7d34a92",
                                        width: 640,
                                        height: 320,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=960\u0026crop=smart\u0026auto=webp\u0026s=1557c8ad97ddaf13b58fd06dd8c4ff3ae26132d3",
                                        width: 960,
                                        height: 480,
                                    },
                                    {
                                        url: "https://external-preview.redd.it/22XmEH-5PaxXxueRpF1RzIQI84y2viJ-zL1YhOqtKTg.jpg?width=1080\u0026crop=smart\u0026auto=webp\u0026s=a58b847693599338ac2943fd45cf0b9f6cc6cc9b",
                                        width: 1080,
                                        height: 540,
                                    },
                                ],
                                variants: {},
                                id: "tInCs51ZR5MkK8UfGgzhr8WaOt9ZzwJQXO2Z9S2Hefc",
                            },
                        ],
                        enabled: false,
                    },
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2fwo",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "17rbt0v",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "Davipb",
                    discussion_type: null,
                    num_comments: 57,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/programming/comments/17rbt0v/eu_to_force_browsers_to_trust_government/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.eff.org/deeplinks/2023/11/article-45-will-roll-back-web-security-12-years",
                    subreddit_subscribers: 5695061,
                    created_utc: 1699532760.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            },
        ],
        before: null,
    },
};
